const endpoints = {
    eventPhoto: '/event-photos',
    profilePhoto: '/profile-photo',
    orgProfile: '/org-profile',
    targetGroup: '/target-groups',
    targetRegion: '/target-regions',
    keyProgramme: '/key-programmes',
    donor: '/donors',
    participant: '/participants',
    proposal: '/proposals',
    objective: '/objectives',
    agenda: '/agenda',
    activity: '/activities',
    activityPlan: '/activity-plans',
    quiz: '/narrative-quiz',
    narrative: '/narrative-reports',
    caseStudy: '/case-studies',
    user: '/users',
    role: '/roles',
    login: '/auth/login',
    logout: '/auth/logout',
    register: '/auth/register',
    resetPassword: '/auth/reset-password',
};

export default endpoints;